---
# tasks file for ams.javasdk
 - name: Update package index
   apt:
    update_cache: yes
   become: true

 - name: Install java version
   apt:
    name: "{{ java_package_name }}={{ java_version }}"
    state: present
   become: true

 - name: Register system architecture
   shell: dpkg --print-architecture
   register: architecture


 #- name: Set the JAVA_HOME environment variable for all users
 - lineinfile:
    dest: /etc/bash.bashrc
    state: present
    line: export JAVA_HOME="/usr/lib/jvm/{{ java_package_name }}-{{ architecture.stdout }}/"
   become: true
