---
# ===============================================================================================
# Ansible playbook for a provisioning a developer VM                                            #
#                                                                                               #
# NOTE:                                                                                         #
# Whenever you are using roles from Ansible Galaxy (https://galaxy.ansible.com/) make sure      #
# to include the role in the file requirements.yml within the root directory of this repo       #
# ===============================================================================================

- hosts: developmentVM

  vars_files:
    - group_vars/vars

  roles:

#**************************************************************************************************************#
# JDKs / Runtime Environments                                                                                  #
#**************************************************************************************************************#

    # ==========================================================================================================
    # Software:         Node.js
    # Author:           geerlingguy
    # Documentation:    https://galaxy.ansible.com/geerlingguy/nodejs/
    # Description:      Installation of Node Package Manager (npm)
    # ==========================================================================================================
    - role: geerlingguy.nodejs
      nodejs_version: "8.x"
      #nodejs_npm_global_packages:
      #  - name: jslint
      #    version: 0.9.3
      #  - name: node-sass

    # ==========================================================================================================
    # Software:          Java JDK
    # Author:            gantsign
    # Documentation:     https://galaxy.ansible.com/gantsign/java/
    # Description:       Installation of Oracles Java Development Kit (JDK)
    # ==========================================================================================================
    - role: gantsign.java
      java_version: '8'
      java_is_default_installation: yes
      java_fact_group_name: java
      java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'

      # You can install multiple versions of Java by copying this role with a different version
    - role: gantsign.java
      java_version: '10'
      java_is_default_installation: no
      java_fact_group_name: java
      java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'


#**************************************************************************************************************#
# Build tools                                                                                                  #
#**************************************************************************************************************#

    # ==========================================================================================================
    # Software:          Maven
    # Author:            gantsign
    # Documentation:     https://galaxy.ansible.com/gantsign/maven/
    # Description:       Installation of Maven (build automation tool)
    # ==========================================================================================================
    - role: gantsign.maven
      maven_version: '3.5.0'

#**************************************************************************************************************#
# Other software                                                                                               #
#**************************************************************************************************************#

    # ==========================================================================================================
    # Software:         Git
    # Author:           geerlingguy
    # Documentation:    https://galaxy.ansible.com/geerlingguy/git/
    # Description:      Installation of the popular version control system 'Git'
    # ==========================================================================================================
    - role: geerlingguy.git
      git_version: "2.16.2"
      # If git is already installed at and older version, force a new source build.
      # Only applies if git_install_from_source is true.
      git_install_from_source: false


    # ==========================================================================================================
    # Software:          Postman
    # Author:            gantsign
    # Documentation:     https://galaxy.ansible.com/gantsign/postman/
    # Description:       Installation of the popular REST Client 'Postman'
    # ==========================================================================================================
    - role: gantsign.postman


    # ==========================================================================================================
    # Software:         Docker
    # Author:           geerlingguy
    # Galaxy URL:       https://galaxy.ansible.com/geerlingguy/docker/
    # Description:      Installation of Docker (operating-system-level virtualization)
    # ==========================================================================================================
    - role: geerlingguy.docker
      docker_edition: 'ce'
      docker_package: "docker-{{ docker_edition }}"
      docker_package_state: latest
      docker_install_compose: true
      docker_compose_version: "1.19.0"
      docker_compose_path: /usr/local/bin/docker-compose
      docker_apt_release_channel: stable
      docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
      docker_yum_repo_url: https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo

    # ==========================================================================================================
    # Software:          Google Chrome
    # Author:            cmprescott
    # Documentation:     https://galaxy.ansible.com/cmprescott/chrome/
    # Description:       Popular web browser by Google
    # ==========================================================================================================
    - role: cmprescott.chrome

#**************************************************************************************************************#
# Messenger / Chat tools                                                                                          #
#**************************************************************************************************************#


    # ==========================================================================================================
    # Software:         Slack
    # Author:           wtanaka
    # Galaxy URL:       https://galaxy.ansible.com/wtanaka/slack/
    # Description:      Popular messenger by Atlassian
    # ==========================================================================================================
    - role: wtanaka.slack

#**************************************************************************************************************#
# Text editors / IDEs                                                                                          #
#**************************************************************************************************************#


    # ==========================================================================================================
    # Software:          Atom
    # Author:            gantsign
    # Documentation:     https://galaxy.ansible.com/gantsign/atom/
    # Description:       Installation of the popular open-source text editor 'Atom'
    # ==========================================================================================================
    - role: gantsign.atom
      users:
        - username: vagrant
          atom_packages:
            - minimap
            - linter
            - atom-beautify
            - file-icons

    # ==========================================================================================================
    # Software:          Sublime Text
    # Author:            jdauphant
    # Documentation:     https://galaxy.ansible.com/jdauphant/sublimetext/
    # Description:       Installation of sublimetext3, a popular commercial editor
    # ==========================================================================================================
    - role: jdauphant.sublimetext


    # ==========================================================================================================
    # Software:          Visual Studio Code
    # Author:            gantsign
    # Documentation:     https://galaxy.ansible.com/gantsign/visual-studio-code/
    # Description:       Installation of Visual Studio Code
    # ==========================================================================================================
    - role: gantsign.visual-studio-code


    # ==========================================================================================================
    # Software:          IntelliJ
    # Author:            gantsign
    # Documentation:     https://galaxy.ansible.com/gantsign/intellij/
    # Description:       Installation of Jetbrain's popular IDE IntelliJ
    # IMPORTANT:         This role requires an installation of Oracles JDK
    # ==========================================================================================================
    - role: gantsign.intellij
      intellij_edition: ultimate





#**************************************************************************************************************#
# Database servers                                                                                             #
#**************************************************************************************************************#

    # ==========================================================================================================
    # Software:          MySQL
    # Author:            geerlingguy
    # Documentation:     https://galaxy.ansible.com/geerlingguy/mysql/
    # Description:       Installation of MySQL database server
    # Notes:             This role is not pulled from the galaxy because of an open issue with the docker
    #                    integration. Until solved, we use the local role we fixed ourselves.
    # ==========================================================================================================
    - role: geerlingguy.mysql
      become: yes
      mysql_root_home: /root
      mysql_root_username: root
      mysql_root_password: root
      mysql_enabled_on_startup: yes

    # ==========================================================================================================
    # Software:          Redis
    # Author:            DavidWittman
    # Documentation:     https://galaxy.ansible.com/davidwittman/redis/
    # Description:       Installation of Redis database server
    # ==========================================================================================================
    - role: DavidWittman.redis
      redis_bind: 127.0.0.1


    # ==========================================================================================================
    # Software:          PostgreSQL
    # Author:            geerlingguy
    # Documentation:     https://galaxy.ansible.com/geerlingguy/postgresql/
    # Description:       Installation of PostgreSQL database server
    # ==========================================================================================================
    - role: geerlingguy.postgresql
      become: yes
      postgresql_databases:
        - name: example_db
      postgresql_users:
        - name: example_user
          password: supersecure


  tasks:

    # ==========================================================================================================
    # Software:          MySQL Workbench
    # Author:            Oracle
    # Documentation:     https://www.mysql.com/products/workbench/
    # Description:       Installation of MySQL workbench
    # ==========================================================================================================
   - name: install mysql workbench
     apt:
      name: mysql-workbench
      state: present

    # ==========================================================================================================
    # Description:       Copying of configuration files eg. from the configuration directory into /opt/config
    # ==========================================================================================================
   - name: copy configuration files
      command: cp -r /vagrant/configuration/ /opt/config
      ignore_errors: yes
      args:
        creates: /opt/configuration

    # ==========================================================================================================
    # Description:       Checkout any project
    # ==========================================================================================================
   - name: checkout code, ignore failure on local changes
     git:
        repo: https://github.com/keniseli/ansible-developer-vm.git
        dest: /home/vagrant/developer-vm
     ignore_errors: yes