- hosts: web
  roles:
    - { role: wtanaka.git }
    - { role: ams.jdk }

  vars_files:
    - group_vars/vars

  environment:
    SAMPLE_ENVIRONMENT_VARIABLE: "{{ variable_from_group_vars }}"
    SECOND_SAMPLE_ENVIRONMENT_VARIABLE: "ams rocks!"
